version: "2"

services:  
  live555:
  # TODO: Change to release image
    image: "gcr.io/test-bai/live555:latest"
    restart: unless-stopped
    volumes:
      - ./test-data:/mnt
    networks:
      - sighthound

  sio:
    image: ${SIO_DOCKER_IMAGE}:${SIO_DOCKER_TAG}-${SIO_ARCH}
    restart: always
    volumes:
      - /data/sighthound/license/sighthound-license.json:/sighthound/sio/share/sighthound-license.json:ro
      - ./sio.json:/sio.json:ro
      - /data/sighthound/media:/data/sighthound/media:rw
      - /data/sighthound/.cache:/root/.sio/modelCache
    env_file:
      - .env
    command: > 
      /sighthound/sio/bin/runPipelineSet /sio.json
    networks:
      - sighthound

networks:
  sighthound:
    name: sighthound
    external: true