version: "2"

services:
  sio:
    container_name: ${SIO_CONTAINER_NAME}${SERVICE_GROUP}
    image: ${SIO_DOCKER_IMAGE}:${SIO_DOCKER_TAG}${SIO_ARCH}
    restart: always
    volumes:
      - ${LICENSE_PATH}/sighthound-license.json:/sighthound/sio/share/sighthound-license.json:ro
      - ./conf/:/etc/sio/:ro
      - ./conf/plugins/:/lib/sio/plugins/:ro
      - ${MEDIA_PATH}:/data/sighthound/media:rw
      - ${SH_BASE}/.cache:/root/.sio/modelCache
    env_file:
      - .env
    entrypoint: /bin/bash
    stdin_open: true
    tty: true
    networks:
      core_sighthound:
        aliases:
          - ${SIO_CONTAINER_NAME}${SERVICE_GROUP}
      sh-device-ui_sh-ui-net:
        aliases:
          - ${SIO_CONTAINER_NAME}${SERVICE_GROUP}

networks:
  core_sighthound:
    external: true
  sh-device-ui_sh-ui-net:
    external: true
