version: "2"

services:  
  sio:
    container_name: ${SIO_CONTAINER_NAME}${SERVICE_GROUP}
    image: ${SIO_DOCKER_IMAGE}:${SIO_DOCKER_TAG}${SH_ARCH}
    restart: always
    volumes:
      - ${LICENSE_PATH}/sighthound-license.json:/sighthound/sio/share/sighthound-license.json:ro
      - ${LICENSE_PATH}/sighthound-license.json:/sighthound/sio/share/license.json:ro
      - ./conf/:/etc/sio/:ro
      - ./conf/:/sighthound/sio/conf:ro
      - ./conf/plugins/:/lib/sio/plugins/:ro
      - ${MEDIA_PATH}:/data/sighthound/media:rw
      - ${SH_BASE}/.cache:/root/.sio/modelCache
    # working_dir: /sighthound/sio # This is default
    env_file:
      - .env
    command: sh -c 'eval "/sighthound/sio/bin/${SIO_APP} ${SIO_ENTRYPOINT} --log ${SIO_LOG_LEVEL} ${SIO_EXTRA_ARGS}"'
    networks:
      core_sighthound:
        aliases:
          - ${SIO_CONTAINER_NAME}${SERVICE_GROUP}
      sh-device-ui_sh-ui-net:
        aliases:
          - ${SIO_CONTAINER_NAME}${SERVICE_GROUP}

networks:
  core_sighthound:
    external: true
  sh-device-ui_sh-ui-net:
    external: true
