version: "3.4"

services:
  rabbitmq:
    image: ${AMQP_DOCKER_IMAGE}:${AMQP_DOCKER_TAG}
    restart: unless-stopped
    volumes:
      - ./conf/definitions.json:/etc/rabbitmq/definitions.json
      - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - rabbitmq_persistent_storage:/var/lib/rabbitmq
    ports:
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - core_sighthound

networks:
  core_sighthound:
    external: true

volumes:
  rabbitmq_persistent_storage:
