version: '3.7'
services:
  aqueductrunner:
    build: .
    container_name: aqueductrunner
    restart: always
    ports:
      - "8554:8554"
    environment:
      - MCP_HOST=mcp
      - MCP_PORT=9097
      - MCP_USERNAME=root
      - MCP_PASSWORD=root
    volumes:
      - ./src:/usr/src/app
      - ./pipelines:/usr/src/app/pipelines
      - ../lib:/usr/src/app/lib
      - ../../..:/data/sighthound
    networks:
      core_sighthound:
        aliases:
          - aqueductrunner

networks:
  core_sighthound:
    external: true