version: "2"

services:
  mcp:
    container_name: ${MCP_CONTAINER_NAME}${SERVICE_GROUP}
    image: ${MCP_DOCKER_IMAGE}:${MCP_DOCKER_TAG}
    restart: unless-stopped
    mem_limit: 1G
    mem_reservation: 512M
    volumes:
      - ${MEDIA_PATH}:/data/sighthound/media:rw
      - ${LOGS_PATH}/mcp:/data/sighthound/logs/mcp:rw
      - ${DB_PATH}:/data/sighthound/db:rw
      - ./conf/mcp.yml:/etc/mcpd/default.json:ro
    ports:
      - "9097:9097"
    env_file:
      - .env
    networks:
      core_sighthound:
        aliases:
          - ${MCP_CONTAINER_NAME}${SERVICE_GROUP}

networks:
  core_sighthound:
    external: true